version: '3.8'

services:
  notice-board:
    build: .
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - PORT=3007
    volumes:
      - notice-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - notice-network

volumes:
  notice-data:
    driver: local

networks:
  notice-network:
    driver: bridge